default_platform(:ios)

platform :ios do

 desc "Run unit tests"

  lane :tests do

    scan(

      scheme: "BookStoreSwiftUIApp",

      clean: true

    )

  end

  desc "Build app"

  lane :build do

    build_app(

      scheme: "BookStoreSwiftUIApp",

      skip_package_ipa: true,

      skip_archive: true

    )

  end

end